export const GET_POKEDEX = 'GET_POKEDEX';
export const GET_POKEDEX_SUCCESS = 'GET_POKEDEX_SUCCESS';
export const GET_POKEDEX_FAILURE = 'GET_POKEDEX_FAILURE';
export const RESET_POKEDEX = 'RESET_POKEDEX';

export const GET_POKEMON = 'GET_POKEMON';
export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMON_FAILURE = 'GET_POKEMON_FAILURE';
